stages:
  load_data:
    cmd: |
      echo "Loading Data"
      python src/stage-01-load-n-save.py
    deps:
      - src/stage-01-load-n-save.py
      - src/utils/utils.py
      - config/config.yaml
    outs:
      - data/cat
      - data/dog

  prepare_base_model:
    cmd: |
      echo "Preparing Base Model"
      python src/stage-02-prepare-base-model.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage-02-prepare-base-model.py
      - src/utils/utils.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
    outs:
      - artifacts/base/updated_VGG16_base_model.h5
      - artifacts/base/VGG16_base_model.h5